import { NextResponse } from 'next/server';
import archiver from 'archiver';
import { Readable } from 'stream';

export async function POST(req: Request) {
  try {
    const { projectName, suggestedStack } = await req.json();

    // 1. Create the Archiver instance (Node Stream)
    const archive = archiver('zip', { zlib: { level: 9 } });

    // 2. Convert Node Stream to Web Stream so Next.js can send it
    const stream = new ReadableStream({
      start(controller) {
        archive.on('data', (chunk) => controller.enqueue(chunk));
        archive.on('end', () => controller.close());
        archive.on('error', (err) => controller.error(err));
      },
    });

    // 3. Add Files to the ZIP
    // README
    const readmeContent = `# ${projectName}\n\nGenerated by Pulse Architect\n\nStack: ${suggestedStack}`;
    archive.append(readmeContent, { name: 'README.md' });

    // Package.json
    const packageJson = JSON.stringify({
      name: projectName.toLowerCase().replace(/\s+/g, '-'),
      version: "1.0.0",
      dependencies: { "next": "latest", "react": "latest" }
    }, null, 2);
    archive.append(packageJson, { name: 'package.json' });

    // Dummy folders
    archive.append('', { name: 'src/app/' });
    archive.append('', { name: 'src/components/' });

    // 4. Finalize (Important: This tells the stream we are done!)
    archive.finalize();

    return new Response(stream, {
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${projectName.replace(/\s+/g, '_')}.zip"`,
      },
    });

  } catch (error: any) {
    console.error('ZIP Error:', error);
    return NextResponse.json({ error: 'Failed to generate ZIP', details: error.message }, { status: 500 });
  }
}